### ISSUE TITLE
Trailing dot in filenames

### ISSUE THREAD

**Issue by darkred3** [hurlenko/mloader#8]
mloader saves images with a trailing dot which causes some issues with image viewer programs I'm using.

**Comment by hurlenko** [comment]
Hi @darkred3,

I wasn't able to reproduce it, can you share a link that causes the issue?

**Comment by darkred3** [comment]
It seems to be happening with every manga as far as I can see. Tested 1007382, 1007365 and 1007374. Both with and without the --raw parameter.
Filenames look like this "SPY x FAMILY-001..png"

**Comment by hurlenko** [comment]
I see, you are running an old version of mloader. This problem was resolved in #6. Run `pip install -U mloader` to update to the latest version. Note that in the most recent version of mloader you need to provide full chapter/title url, not the id. If you still want to use ids, pass them to the `-c <chapter_id>` or `-t <title_id>` cli options
